soundOverrides:
  creeper: "minecraft:entity.creeper.primed"
  #wither_skeleton: "minecraft:entity.wither_skeleton.death"
  ender_dragon: "minecraft:entity.ender_dragon.growl"
  #wither: "minecraft:entity.wither.spawn"
  #ghast: "minecraft:entity.ghast.scream"
  phantom: "minecraft:entity.phantom.swoop"
  piglin_brute: "minecraft:entity.piglin_brute.angry"
  #illusioner: "minecraft:entity.illusioner.prepare_blindness"
  illusioner: "minecraft:entity.illusioner.cast_spell"
  evoker: "minecraft:entity.evoker.prepare_summon"
  #evoker: "minecraft:entity.evoker.prepare_attack"
  #evoker: "minecraft:entity.evoker.prepare_wololo"