name: CustomMobHeads
version: 1.0.2
main: com.portix.custommobheads.Main
api-version: 1.21

commands:
  gethead:
    #description: Gives a custom mob head
    #usage: /gethead <mob_id> [variant_path]
    description: Gives a custom mob head to a player
    usage: /gethead <player> <mob_id> [variant] [subvariant]
    permission: custommobheads.gethead
    permission-message: You do not have permission to use this command.
